---
# This playbook deploys the whole application stack in this site.

- name: launch aws servers
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  tags: provisioning
  
  roles:
  - launch

- name: run docker
  hosts: tag_Name_webserver
  remote_user: "{{ remote_user }}"
  become: True
  gather_facts: False

  roles:
  - docker

- name: running prometheus
  hosts: tag_Name_webserver
  remote_user: "{{ remote_user }}"
  become: True
  gather_facts: False

  roles:
  - prom
