---
# roles/launch/tasks/main.yml
- name: Launch the new EC2 Instance
  local_action:
    module: ec2
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    count: "{{ count }}"
    instance_tags:
      Name: webserver # capitalize because it's AWS convention
      container: docker
    volumes: "{{ volumes }}"
  register: ec2

#- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
#  local_action: lineinfile
#                dest="./hosts"
#                regexp={{ item.public_ip }}
#                insertafter="[webserver]" line={{ item.public_ip }}
#  with_items: "{{ ec2.instances }}"


- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 30
    timeout: 300
    state: started
  with_items: "{{ ec2.instances }}"
